# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
client:
    type: rest
    resource: App\Controller\ClientController
    prefix: api
province:
    type: rest
    resource: App\Controller\ProvinceController
    prefix: api
etatcommande:
    type: rest
    resource: App\Controller\EtatCommandeController
    prefix: api
categorie:
    type: rest
    resource: App\Controller\CategorieController
    prefix: api
meuble:
    type: rest
    resource: App\Controller\MeubleController
    prefix: api
stock:
    type: rest
    resource: App\Controller\StockController
    prefix: api
commande:
    type: rest
    resource: App\Controller\CommandeController
    prefix: api